const admin = require('firebase-admin');
const serviceAccount = require('../service-account.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

const hobbies = [
  // ─── CREATIVE ──────────────────────────────────────────
  {
    id: 'watercolor-painting',
    data: {
      id: 'watercolor-painting',
      name: 'Watercolor Painting',
      tagline: 'Where creativity meets tranquility',
      category: 'Art & Craft',
      subcategory: 'Painting',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 257,
      costRange: 'low',
      indoorOutdoor: 'indoor',
      soloGroup: 'solo',
      emoji: '🎨',
      tags: ['creative', 'relaxing', 'artistic', 'mindful'],
      description: 'Create beautiful, flowing artwork with watercolors. This calming hobby lets you express creativity through soft washes of color and delicate brushwork.',
      starterKit: [
        'Watercolor paint set',
        'Watercolor paper pad',
        'Round brushes set',
        'Water containers',
        'Paper towels',
        'Palette',
      ],
      popularIn: ['Abu Dhabi', 'Dubai'],
      hasLearningPath: true,
      hasJourneyTemplate: true,
      imageUrl: '',
      matchTags: ['creative', 'indoor', 'solo', 'relaxation', 'art'],
    },
  },
  {
    id: 'photography',
    data: {
      id: 'photography',
      name: 'Photography',
      tagline: 'Capture the world through your lens',
      category: 'Art & Craft',
      subcategory: 'Photography',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 550,
      costRange: 'medium',
      indoorOutdoor: 'both',
      soloGroup: 'solo',
      emoji: '📸',
      tags: ['creative', 'outdoor', 'artistic', 'technical'],
      description: 'Discover the art of capturing moments. From smartphone photography to DSLR, learn composition, lighting, and editing to tell visual stories.',
      starterKit: [
        'Camera or smartphone',
        'Memory card',
        'Camera bag',
        'Editing app (Lightroom Mobile)',
        'Tripod (optional)',
      ],
      popularIn: ['Dubai', 'Abu Dhabi'],
      hasLearningPath: false,
      hasJourneyTemplate: true,
      imageUrl: '',
      matchTags: ['creative', 'outdoor', 'solo', 'technical', 'art'],
    },
  },
  {
    id: 'pottery-ceramics',
    data: {
      id: 'pottery-ceramics',
      name: 'Pottery & Ceramics',
      tagline: 'Shape clay into something beautiful',
      category: 'Art & Craft',
      subcategory: 'Pottery',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 294,
      costRange: 'medium',
      indoorOutdoor: 'indoor',
      soloGroup: 'both',
      emoji: '🏺',
      tags: ['creative', 'tactile', 'meditative', 'hands-on'],
      description: 'A calming, hands-on craft where you shape clay into bowls, mugs, and vases. Beginner-friendly and deeply meditative.',
      starterKit: [
        'Air-dry clay',
        'Pottery tools set',
        'Turntable',
        'Sponge',
        'Canvas work mat',
        'Glaze set',
      ],
      popularIn: ['Dubai', 'Abu Dhabi'],
      hasLearningPath: true,
      hasJourneyTemplate: true,
      imageUrl: '',
      matchTags: ['creative', 'indoor', 'tactile', 'relaxation', 'hands-on'],
    },
  },
  {
    id: 'calligraphy',
    data: {
      id: 'calligraphy',
      name: 'Calligraphy',
      tagline: 'Turn words into art',
      category: 'Art & Craft',
      subcategory: 'Lettering',
      difficulty: 'beginner',
      timePerWeek: '2 hrs/wk',
      timeMinutes: 120,
      estimatedCostAED: 110,
      costRange: 'low',
      indoorOutdoor: 'indoor',
      soloGroup: 'solo',
      emoji: '✒️',
      tags: ['creative', 'meditative', 'artistic', 'writing'],
      description: 'The art of beautiful writing. Learn brush calligraphy to create stunning lettered pieces for cards, gifts, and home décor.',
      starterKit: [
        'Brush pen set (Tombow)',
        'Calligraphy paper pad',
        'Practice sheets',
        'Fine liner pens',
      ],
      popularIn: ['Abu Dhabi', 'Dubai'],
      hasLearningPath: true,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['creative', 'indoor', 'solo', 'meditative', 'art'],
    },
  },
  {
    id: 'sketching-drawing',
    data: {
      id: 'sketching-drawing',
      name: 'Sketching & Drawing',
      tagline: 'Bring your imagination to life on paper',
      category: 'Art & Craft',
      subcategory: 'Drawing',
      difficulty: 'beginner',
      timePerWeek: '2 hrs/wk',
      timeMinutes: 120,
      estimatedCostAED: 92,
      costRange: 'low',
      indoorOutdoor: 'indoor',
      soloGroup: 'solo',
      emoji: '✏️',
      tags: ['creative', 'relaxing', 'artistic', 'portable'],
      description: 'The most accessible art form. Sketch anywhere with just a pencil and paper. Learn observation, proportion, and shading to draw anything you see.',
      starterKit: [
        'Sketchbook (A5 or A4)',
        'Pencil set (HB, 2B, 4B, 6B)',
        'Kneaded eraser',
        'Blending stumps',
        'Fine liner set',
      ],
      popularIn: ['Abu Dhabi', 'Dubai'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['creative', 'indoor', 'solo', 'relaxation', 'art'],
    },
  },
  {
    id: 'acrylic-painting',
    data: {
      id: 'acrylic-painting',
      name: 'Acrylic Painting',
      tagline: 'Bold colours, endless possibilities',
      category: 'Art & Craft',
      subcategory: 'Painting',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 330,
      costRange: 'medium',
      indoorOutdoor: 'indoor',
      soloGroup: 'solo',
      emoji: '🖌️',
      tags: ['creative', 'colourful', 'artistic', 'expressive'],
      description: 'Fast-drying, forgiving, and vibrant. Acrylic painting is perfect for beginners who want bold results without the complexity of oils.',
      starterKit: [
        'Acrylic paint set (12 colours)',
        'Canvas boards (pack of 5)',
        'Brush set',
        'Palette',
        'Easel (optional)',
      ],
      popularIn: ['Dubai', 'Abu Dhabi'],
      hasLearningPath: true,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['creative', 'indoor', 'solo', 'expressive', 'art'],
    },
  },

  // ─── ACTIVE ────────────────────────────────────────────
  {
    id: 'running',
    data: {
      id: 'running',
      name: 'Running',
      tagline: 'Your city is your gym',
      category: 'Fitness',
      subcategory: 'Cardio',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 367,
      costRange: 'medium',
      indoorOutdoor: 'outdoor',
      soloGroup: 'both',
      emoji: '🏃',
      tags: ['fitness', 'outdoor', 'energetic', 'social'],
      description: 'The simplest and most effective way to get fit. Start with a 5K plan and build to longer distances at your own pace.',
      starterKit: [
        'Running shoes',
        'Moisture-wicking socks',
        'Running shorts/leggings',
        'Running app (Nike Run Club)',
        'Water bottle',
      ],
      popularIn: ['Abu Dhabi', 'Dubai'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['fitness', 'outdoor', 'solo', 'energetic', 'health'],
    },
  },
  {
    id: 'yoga',
    data: {
      id: 'yoga',
      name: 'Yoga',
      tagline: 'Strength, flexibility, and inner calm',
      category: 'Fitness',
      subcategory: 'Mind-Body',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 220,
      costRange: 'low',
      indoorOutdoor: 'both',
      soloGroup: 'both',
      emoji: '🧘',
      tags: ['fitness', 'mindful', 'relaxing', 'flexible'],
      description: 'A practice that unites body, mind, and breath. Whether you want flexibility, strength, or stress relief, yoga adapts to every level.',
      starterKit: [
        'Yoga mat',
        'Yoga blocks (2)',
        'Yoga strap',
        'Comfortable clothes',
        'YouTube channel (Yoga with Adriene)',
      ],
      popularIn: ['Dubai', 'Abu Dhabi'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['fitness', 'indoor', 'solo', 'mindful', 'relaxation'],
    },
  },
  {
    id: 'cycling',
    data: {
      id: 'cycling',
      name: 'Cycling',
      tagline: 'Explore further, faster',
      category: 'Fitness',
      subcategory: 'Cardio',
      difficulty: 'beginner',
      timePerWeek: '4 hrs/wk',
      timeMinutes: 240,
      estimatedCostAED: 1470,
      costRange: 'high',
      indoorOutdoor: 'outdoor',
      soloGroup: 'both',
      emoji: '🚴',
      tags: ['fitness', 'outdoor', 'social', 'adventurous'],
      description: 'Explore the UAE on two wheels. Cycling is low-impact, social, and lets you cover ground you could never reach on foot.',
      starterKit: [
        'Bicycle (entry-level road or hybrid)',
        'Helmet (essential)',
        'Cycling gloves',
        'Water bottle cage',
        'Basic repair kit',
      ],
      popularIn: ['Abu Dhabi', 'Dubai'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['fitness', 'outdoor', 'social', 'adventurous', 'health'],
    },
  },
  {
    id: 'swimming',
    data: {
      id: 'swimming',
      name: 'Swimming',
      tagline: 'The perfect full-body workout',
      category: 'Fitness',
      subcategory: 'Water Sports',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 293,
      costRange: 'medium',
      indoorOutdoor: 'both',
      soloGroup: 'solo',
      emoji: '🏊',
      tags: ['fitness', 'relaxing', 'full-body', 'meditative'],
      description: 'A low-impact, full-body workout that is gentle on joints. Perfect for all fitness levels and ideal for the UAE climate.',
      starterKit: [
        'Swimsuit/trunks',
        'Goggles',
        'Swim cap',
        'Kickboard',
        'Pull buoy',
      ],
      popularIn: ['Dubai', 'Abu Dhabi'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['fitness', 'indoor', 'solo', 'relaxation', 'health'],
    },
  },
  {
    id: 'rock-climbing',
    data: {
      id: 'rock-climbing',
      name: 'Rock Climbing',
      tagline: 'The ultimate mind-body challenge',
      category: 'Fitness',
      subcategory: 'Adventure',
      difficulty: 'beginner',
      timePerWeek: '2 hrs/wk',
      timeMinutes: 120,
      estimatedCostAED: 550,
      costRange: 'medium',
      indoorOutdoor: 'both',
      soloGroup: 'social',
      emoji: '🧗',
      tags: ['fitness', 'social', 'adventurous', 'challenging'],
      description: 'A full-body workout that is also a puzzle. Indoor climbing walls make it accessible for beginners in Dubai and Abu Dhabi.',
      starterKit: [
        'Climbing shoes (rent first)',
        'Chalk bag',
        'Harness (rent first)',
        'Day pass to climbing gym',
      ],
      popularIn: ['Dubai', 'Abu Dhabi'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['fitness', 'social', 'adventurous', 'challenging', 'outdoor'],
    },
  },

  // ─── MUSIC ─────────────────────────────────────────────
  {
    id: 'guitar',
    data: {
      id: 'guitar',
      name: 'Guitar',
      tagline: 'From first chord to favourite songs',
      category: 'Music',
      subcategory: 'String Instruments',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 735,
      costRange: 'medium',
      indoorOutdoor: 'indoor',
      soloGroup: 'both',
      emoji: '🎸',
      tags: ['music', 'creative', 'social', 'expressive'],
      description: 'Learn to play guitar and unlock a lifetime of music. Start with chords, progress to songs, and discover why guitar is the world\'s most popular instrument.',
      starterKit: [
        'Acoustic guitar (entry-level)',
        'Guitar picks (variety pack)',
        'Tuner clip',
        'Extra strings (pack)',
        'Guitar app (Yousician or Justin Guitar)',
      ],
      popularIn: ['Dubai', 'Abu Dhabi'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['music', 'creative', 'indoor', 'social', 'expressive'],
    },
  },
  {
    id: 'piano',
    data: {
      id: 'piano',
      name: 'Piano',
      tagline: 'The foundation of all music',
      category: 'Music',
      subcategory: 'Keyboard Instruments',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 1100,
      costRange: 'high',
      indoorOutdoor: 'indoor',
      soloGroup: 'solo',
      emoji: '🎹',
      tags: ['music', 'creative', 'disciplined', 'classical'],
      description: 'The piano teaches you to read music, develop rhythm, and understand harmony. A rewarding long-term hobby with apps making it more accessible than ever.',
      starterKit: [
        'Digital keyboard (61 keys minimum)',
        'Sustain pedal',
        'Piano bench or stool',
        'Headphones (for practice)',
        'App: Simply Piano or Flowkey',
      ],
      popularIn: ['Dubai', 'Abu Dhabi'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['music', 'creative', 'indoor', 'solo', 'disciplined'],
    },
  },
  {
    id: 'singing',
    data: {
      id: 'singing',
      name: 'Singing',
      tagline: 'Your voice is an instrument',
      category: 'Music',
      subcategory: 'Vocals',
      difficulty: 'beginner',
      timePerWeek: '2 hrs/wk',
      timeMinutes: 120,
      estimatedCostAED: 110,
      costRange: 'low',
      indoorOutdoor: 'indoor',
      soloGroup: 'both',
      emoji: '🎤',
      tags: ['music', 'expressive', 'social', 'creative'],
      description: 'Everyone can learn to sing better. Vocal training improves pitch, range, and confidence. One of the most expressive and accessible hobbies.',
      starterKit: [
        'Vocal warm-up app (Vanido)',
        'Bluetooth speaker',
        'Microphone (optional)',
        'Online vocal coach (YouTube)',
      ],
      popularIn: ['Dubai', 'Abu Dhabi'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['music', 'expressive', 'indoor', 'social', 'creative'],
    },
  },

  // ─── NATURE ────────────────────────────────────────────
  {
    id: 'gardening',
    data: {
      id: 'gardening',
      name: 'Gardening',
      tagline: 'Grow something beautiful',
      category: 'Nature',
      subcategory: 'Plants',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 184,
      costRange: 'low',
      indoorOutdoor: 'both',
      soloGroup: 'solo',
      emoji: '🌱',
      tags: ['nature', 'relaxing', 'mindful', 'rewarding'],
      description: 'Grow your own herbs, flowers, or vegetables. Gardening reduces stress, connects you to nature, and is especially rewarding in the UAE\'s climate.',
      starterKit: [
        'Plant pots (variety of sizes)',
        'Potting soil',
        'Basic tool set (trowel, fork)',
        'Starter seeds or seedlings',
        'Watering can',
      ],
      popularIn: ['Abu Dhabi', 'Dubai'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['nature', 'indoor', 'solo', 'relaxation', 'mindful'],
    },
  },
  {
    id: 'hiking',
    data: {
      id: 'hiking',
      name: 'Hiking',
      tagline: 'Explore the UAE on foot',
      category: 'Nature',
      subcategory: 'Outdoor Adventure',
      difficulty: 'beginner',
      timePerWeek: '4 hrs/wk',
      timeMinutes: 240,
      estimatedCostAED: 551,
      costRange: 'medium',
      indoorOutdoor: 'outdoor',
      soloGroup: 'both',
      emoji: '🥾',
      tags: ['nature', 'fitness', 'social', 'adventurous'],
      description: 'The UAE has stunning hiking trails from Jebel Hafeet to Wadi Ghul. Hiking combines fitness, nature, and exploration in one rewarding activity.',
      starterKit: [
        'Hiking boots or trail shoes',
        'Hydration pack (2L)',
        'Sun protection (hat, SPF)',
        'Trekking poles (optional)',
        'Trail app (AllTrails)',
      ],
      popularIn: ['Abu Dhabi', 'Dubai'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['nature', 'outdoor', 'social', 'fitness', 'adventurous'],
    },
  },
  {
    id: 'birdwatching',
    data: {
      id: 'birdwatching',
      name: 'Birdwatching',
      tagline: 'Discover the wildlife on your doorstep',
      category: 'Nature',
      subcategory: 'Wildlife',
      difficulty: 'beginner',
      timePerWeek: '2 hrs/wk',
      timeMinutes: 120,
      estimatedCostAED: 551,
      costRange: 'medium',
      indoorOutdoor: 'outdoor',
      soloGroup: 'both',
      emoji: '🦜',
      tags: ['nature', 'mindful', 'relaxing', 'educational'],
      description: 'The UAE is on a major migratory flyway making it a birdwatcher\'s paradise. A meditative hobby that deepens your connection to the natural world.',
      starterKit: [
        'Binoculars (8x42 recommended)',
        'Field guide (Birds of the Middle East)',
        'Notebook and pen',
        'App: eBird or Merlin',
        'Comfortable walking shoes',
      ],
      popularIn: ['Abu Dhabi', 'Dubai'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['nature', 'outdoor', 'solo', 'mindful', 'relaxation'],
    },
  },

  // ─── MIND ──────────────────────────────────────────────
  {
    id: 'chess',
    data: {
      id: 'chess',
      name: 'Chess',
      tagline: 'The game of infinite possibilities',
      category: 'Mind Games',
      subcategory: 'Strategy',
      difficulty: 'beginner',
      timePerWeek: '2 hrs/wk',
      timeMinutes: 120,
      estimatedCostAED: 147,
      costRange: 'low',
      indoorOutdoor: 'indoor',
      soloGroup: 'both',
      emoji: '♟️',
      tags: ['mind', 'strategic', 'social', 'competitive'],
      description: 'The world\'s greatest strategy game. Chess sharpens critical thinking, patience, and pattern recognition. Play online or find a local club.',
      starterKit: [
        'Chess set (board + pieces)',
        'App: Chess.com or Lichess (free)',
        'Chess clock (for competitive play)',
        'Beginner book: Bobby Fischer Teaches Chess',
      ],
      popularIn: ['Dubai', 'Abu Dhabi'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['mind', 'indoor', 'social', 'strategic', 'competitive'],
    },
  },
  {
    id: 'reading',
    data: {
      id: 'reading',
      name: 'Reading',
      tagline: 'A thousand lives in one',
      category: 'Mind Games',
      subcategory: 'Literature',
      difficulty: 'beginner',
      timePerWeek: '3 hrs/wk',
      timeMinutes: 180,
      estimatedCostAED: 73,
      costRange: 'low',
      indoorOutdoor: 'indoor',
      soloGroup: 'solo',
      emoji: '📚',
      tags: ['mind', 'relaxing', 'educational', 'portable'],
      description: 'Reading builds empathy, vocabulary, and knowledge. Whether fiction or non-fiction, reading is the most accessible and rewarding lifelong hobby.',
      starterKit: [
        'Kindle or e-reader (optional)',
        'Goodreads account (free)',
        'Library card (free)',
        'Bookmark',
        'Reading lamp',
      ],
      popularIn: ['Abu Dhabi', 'Dubai'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['mind', 'indoor', 'solo', 'relaxation', 'educational'],
    },
  },
  {
    id: 'meditation',
    data: {
      id: 'meditation',
      name: 'Meditation',
      tagline: 'Find your calm in a busy world',
      category: 'Mind Games',
      subcategory: 'Mindfulness',
      difficulty: 'beginner',
      timePerWeek: '2 hrs/wk',
      timeMinutes: 120,
      estimatedCostAED: 55,
      costRange: 'low',
      indoorOutdoor: 'indoor',
      soloGroup: 'solo',
      emoji: '🧠',
      tags: ['mind', 'mindful', 'relaxing', 'health'],
      description: 'A daily meditation practice reduces stress, improves focus, and builds emotional resilience. Just 10 minutes a day can transform your mental wellbeing.',
      starterKit: [
        'App: Headspace or Calm (free trial)',
        'Meditation cushion or pillow',
        'Timer',
        'Quiet space',
        'Journal (optional)',
      ],
      popularIn: ['Abu Dhabi', 'Dubai'],
      hasLearningPath: false,
      hasJourneyTemplate: false,
      imageUrl: '',
      matchTags: ['mind', 'indoor', 'solo', 'mindful', 'relaxation'],
    },
  },
];

async function seed() {
  console.log('Seeding hobbies collection...');
  for (const hobby of hobbies) {
    await db.collection('hobbies').doc(hobby.id).set(hobby.data);
    console.log(`✅ Seeded: ${hobby.data.name}`);
  }
  console.log(`\nDone! ${hobbies.length} hobbies seeded.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Error:', err);
  process.exit(1);
});